name: recipe
properties:
  - name: title
    type: string
  - name: image
    type: string
  - name: description
    type: string
  - name: ingredients
    type: array
    items:
      type: object
      properties:
        - name: title
          type: string
        - name: quantity
          type: integer
        - name: unit
          type: string
